### ISSUE TITLE
Example for quality scenarios are not really quality scenarios

### ISSUE THREAD

**Issue by ewolff** [arc42/arc42.org-site#43]
https://docs.arc42.org/examples/quality-htmlsc-2/ and https://docs.arc42.org/examples/quality-tpu-1/ are not really quality scenarios. As https://github.com/arc42/quality-requirements/ points out, there should be a business goal, an event, a reaction, and a metric for each quality scenario. Usually none of these is present. This is misleading. Until fixed I suggest to remove these examples. They do more harm than good.

**Comment by gernotstarke** [comment]
thanx Eberhard, it seems I'm more of a pragmatic than you are... and some people even told me these examples helped. 
In case you have better examples, I'd be most grateful for any PR (with the side effect that you'd become an arc42 contributor :-)

**Comment by ewolff** [comment]
Thanks for clarifying.
