### ISSUE TITLE
Place link to contact page more prominently

### ISSUE THREAD

**Issue by Per-Starke** [arc42/arc42.org-site#69]
Currently, I find it very hard to find the contact page, although I consider this important, contact page should always be easy to find! Might want to change that?

**Comment by gernotstarke** [comment]
add to top-level navbar? 

Not sure if I like that...

**Comment by Per-Starke** [comment]
@gernotstarke Or maybe add a button on the start-page?  Either below the feature rows or directly in the header, next to the "Overview" and "German page" buttons? Or add to the footer?

**Comment by gernotstarke** [comment]
let's try the button in the header, on both arc42.de and arc42.org
