### ISSUE TITLE
arc42-shop: create "Turnbeutel" with WHITE logo

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42.org-site#89]
and try to replace some of the "strange" colors (red, green) with more subtle ones...

**Comment by Per-Starke** [comment]
Done, you can [get the bag with the white logo here](https://arc42.myspreadshop.de/arc42+logo+white-A6574cf774458e812ad64fb39?productType=1155&sellable=zryNoZNpnQHxJEQm8Jol-1155-33&appearance=737&size=29). Available in nice subtle colors: grey, black, light-blue, and dark-blue
